### ISSUE TITLE
[feat] replace docker-run-action@v3 by azure-cli-action

### ISSUE THREAD

**Issue by schwichti** [dspace-group/simphera-reference-architecture-azure#61]
Use https://github.com/marketplace/actions/azure-cli-action instead of this action:
```yaml
      - uses: addnab/docker-run-action@v3
        with:
          image: zenika/terraform-azure-cli:latest
          options: -v ${{ github.workspace }}:/src
          run: chmod +x /src/hooks/validate_tfvars.sh && /src/hooks/validate_tfvars.sh
```
